[package]
name = "mnist_recognition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mnist = "0.5.0"
ndarray = { version = "0.14", matrixmultiply_threading = true}
rand = "0.8"

